import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "YumeAI App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        {children}
        <Toaster 
         position="top-right"
          duration={4000}
          toastOptions={{
            style: {
              fontSize: "1rem",         
              padding: "0.75rem 1.25rem", 
              borderRadius: "0.5rem", 
              maxWidth: "90vw",          
              boxSizing: "border-box",    
            },
          }}/>
          </ThemeProvider>
      </body>
    </html>
  );
}
